### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-v2f5e#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by pratikbarjatya** [comment]
<img width="1344" alt="Screenshot 2022-08-08 at 1 38 10 PM" src="https://user-images.githubusercontent.com/6903770/183371430-95909f1d-abf3-4da7-b8cd-565c2bd37d6a.png">

Can I raise a PR from my Fork for this?
